categories:
- Metabolomics Visualization
description: A van Krevelen Diagram tool for MS data
long_description: 
name: vkmz
owner: eslerm
remote_repository_url: https://github.com/HegemanLab/vkmz
type: unrestricted
