name: vkmz
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- python-dateutil=2.3=py27_0
- asn1crypto=0.22.0=py27_0
- blas=1.1=openblas
- ca-certificates=2017.11.5=0
- certifi=2017.11.5=py27_0
- cffi=1.11.2=py27_0
- chardet=3.0.4=py27_0
- cryptography=2.1.4=py27_0
- decorator=4.1.2=py27_0
- enum34=1.1.6=py27_1
- idna=2.6=py27_1
- ipaddress=1.0.18=py27_0
- libffi=3.2.1=3
- ncurses=5.9=10
- numpy=1.14.0=py27_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2n=0
- pandas=0.22.0=py27_0
- pip=9.0.1=py27_1
- plotly=2.2.3=py27_0
- pycparser=2.18=py27_0
- pyopenssl=17.4.0=py27_0
- pysocks=1.6.8=py27_1
- python=2.7.14=4
- pytz=2017.3=py_2
- readline=7.0=0
- requests=2.18.4=py27_1
- setuptools=38.4.0=py27_0
- six=1.11.0=py27_1
- sqlite=3.20.1=2
- tk=8.6.7=0
- urllib3=1.22=py27_0
- wheel=0.30.0=py27_2
- zlib=1.2.11=0
- libgfortran=3.0.0=1
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - click==6.7
  - first==2.0.1
  - pathlib==1.0.1
  - pew==0.1.26
  - pip-tools==1.9.0
  - pipenv==6.2.2
  - pythonz-bd==1.11.4
  - semver==2.7.8
  - shutilwhich==1.1.0
  - virtualenv==15.1.0
  - virtualenv-clone==0.2.6

