{% set version = "1.3.0" %}
#{% set sha256 = "fb705cc4bc926a903e4d640bb0de6e400198d94745ece51adc5c935dd5605627" %}

package:
  name: 'vkmz'
  version: {{ version }}

source:
  url: https://github.com/HegemanLab/vkmz/archive/v{{ version }}.tar.gz
#  sha256: {{ sha256 }}

build:
  number: 0
  script: mkdir -p $PREFIX/bin $PREFIX/share $PREFIX/info && cp vkmz.py $PREFIX/bin && cp -R databsaes $PREFIX/share && cp -R test-data $PREFIX/share && cp -R d3.html $PREFIX/share && cp LICENSE $PREFIX/info && cp README* $PREFIX/info

requirements:
  host:
    - python 3.6.*
    - setuptools
  run:
    - python 3.6.*

test:
  commands:
    - vkmz.py --help

about:
  home: https://github.com/HegemanLab/vkmz
  license: MIT License
  summary: 'vkmz: metabolomics formula prediction and van Krevelen diagram generation'
  license_family: MIT

