{% set version = "1.3.0" %}

package:
  name: vkmz 
  version: {{ version }}

source:
  git_url: https://github.com/HegemanLab/VKMZ.git
  git_tag: master

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python 3.6.*
    - setuptools
  run:
    - python 3.6.*

test:
  imports:
    - vkmz
  commands:
    - vkmz -help

about:
  home: https://github.com/HegemanLab/VKMZ
  license: MIT License
  summary: 'VKMZ: metabolomics formula prediction and van Krevelen diagram generation'
  license_family: MIT
